### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by DanTheMan827** [Mte90/Game-Genie-Good-Guy#6]
There's no code license attached.

**Comment by Mte90** [comment]
You are right, the issue is that the original source code didn't have any license.
It was just attached with the software for windows with no license, so I didn't add any license because I don't know how to handle this case.

**Comment by DanTheMan827** [comment]
So I asked Kyle and this is the response I received

    I hadn't ever considered bothering with a license. Have fun with it. The compiled code has no dependencies. That was my motivation for revisiting the application CCCGP. If you come up with something fun please post your own sources.
    
    Here is someone else who was playing around as well:
    https://github.com/Mte90/Game-Genie-Good-Guy
    
    Seeya!
    Kyle

**Comment by Mte90** [comment]
So I think that I can release it as I want as GPLv3 I think that is the best option.

**Comment by Mte90** [comment]
I added a license to the repo :-)
